# Generated by Django 4.2 on 2023-05-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_warehouseuser_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouseuser',
            old_name='is_verified',
            new_name='is_email_verified',
        ),
        migrations.AddField(
            model_name='warehouseuser',
            name='verification_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
