# Generated by Django 4.2 on 2023-05-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_is_verified_warehouseuser_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
