# Generated by Django 4.2 on 2023-05-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_warehouseuser_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='warehouseuser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
