# Generated by Django 4.2 on 2023-05-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_warehouse_storage_space_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='security',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='services_offered',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='equipment',
            field=models.ManyToManyField(blank=True, null=True, to='core.equipment'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='security',
            field=models.ManyToManyField(blank=True, null=True, to='core.security'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='services_offered',
            field=models.ManyToManyField(blank=True, null=True, to='core.services_offered'),
        ),
    ]
