# Generated by Django 4.2 on 2023-05-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_warehouse_equipment_remove_warehouse_security_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='company_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
