# Generated by Django 4.2 on 2023-05-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_warehouse_equipment_remove_warehouse_security_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='coordinates',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
