# Generated by Django 4.2 on 2023-05-03 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_booking_company_name'),
        ('core', '0004_warehouse_coordinates'),
    ]

    operations = [
    ]
