# Generated by Django 4.2 on 2023-05-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_20230503_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='coordinates',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='equipment',
            field=models.ManyToManyField(blank=True, to='core.equipment'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='security',
            field=models.ManyToManyField(blank=True, to='core.security'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='services_offered',
            field=models.ManyToManyField(blank=True, to='core.services_offered'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='storage_space_type',
            field=models.ManyToManyField(blank=True, to='core.storage_space_type'),
        ),
    ]
