# Generated by Django 4.2 on 2023-05-04 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_anonymoususer_alter_booking_business_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='company_name',
        ),
    ]
