# Generated by Django 4.2 on 2023-05-08 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_invoice_anonymous_user_alter_invoice_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='anonymous_user',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='anonymous_user',
        ),
        migrations.DeleteModel(
            name='AnonymousUser',
        ),
    ]
