# Generated by Django 4.2 on 2023-05-08 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_remove_booking_anonymous_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
