# Generated by Django 4.2 on 2023-05-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_warehouse_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='business_rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='warehouse_owner_rating',
            field=models.FloatField(),
        ),
    ]
