# Generated by Django 4.2 on 2023-05-14 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_rating_warehouse_owner_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='rating',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_booking', to='core.booking'),
        ),
    ]
