# Generated by Django 4.2 on 2023-05-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_rating_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='business_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='business_review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
