# Generated by Django 4.2 on 2023-05-15 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_rating_business_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_invoice', to='core.booking'),
        ),
    ]
